name: ci

on: [ push, pull_request ]

jobs:
 lint:
  runs-on: ubuntu-latest
  steps:
  - name: Checkout
    uses: actions/checkout@v2
  - name: Set up Python 3.9
    uses: actions/setup-python@v2
    with:
     python-version: 3.9
  - run: pip install mypy
  - run: mypy --install-types
  - run: pip install pylint
  - run: pip install requests
  - run: pip install sseclient
  - run: pylint nanoleafapi/nanoleaf nanoleafapi/discovery nanoleafapi/digital_twin
  - run: mypy nanoleafapi/nanoleaf.py nanoleafapi/discovery.py nanoleafapi/digital_twin.py